// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	minio "github.com/minio/minio-go/v7"
	mock "github.com/stretchr/testify/mock"
)

// Option is an autogenerated mock type for the Option type
type Option struct {
	mock.Mock
}

// Execute provides a mock function with given fields: mn
func (_m *Option) Execute(mn *minio.Options) error {
	ret := _m.Called(mn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*minio.Options) error); ok {
		r0 = rf(mn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOption creates a new instance of Option. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *Option {
	mock := &Option{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
